In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
arr=np.array([10,20,30,40,50])

In [4]:
print(arr)

[10 20 30 40 50]

In [5]:
print("Shape of the array:", arr.shape)

Shape of the array: (5,)

In [6]:
Series=pd.Series([1,2,3,4,5])

In [7]:
print(Series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:

data ={"Name":["a","b","c","d","e"],
"age":[20,21,19,22,20],
"Marks":[85,90,70,92,88]}

In [9]:
print(data)

{'Name': ['a', 'b', 'c', 'd', 'e'], 'age': [20, 21, 19, 22, 20], 'Marks': [85, 90, 70, 92, 88]}

In [22]:
csv_df=pd.read_csv("C:/Users/arthi/OneDrive/Dokumen/titanic2.csv")

In [17]:
excel_df=pd.read_excel("C:/Users/arthi/Downloads/Sample - Superstore.xls")

In [18]:
excel_df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2022-103800,2022-01-03,2022-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2022-112326,2022-01-04,2022-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2022-112326,2022-01-04,2022-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2022-112326,2022-01-04,2022-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2022-141817,2022-01-05,2022-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [19]:
excel_df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10189,10190,US-2025-143259,2025-12-30,2026-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2025-115427,2025-12-30,2026-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2025-156720,2025-12-30,2026-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2025-143259,2025-12-30,2026-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2025-143500,2025-12-30,2026-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [23]:
csv_df.head()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size
0,791,792,0,1,0.2000,0.050749,0,1,0,0.0
1,792,793,0,0,0.3500,0.135753,0,0,1,1.0
2,793,794,0,1,0.3500,0.059914,1,0,0,0.0
3,794,795,0,1,0.3125,0.015412,0,0,1,0.0
4,795,796,0,1,0.4875,0.025374,0,1,0,0.0

In [24]:
csv_df.tail()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size
95,886,887,0,1,0.3375,0.025374,0,1,0,0.0
96,887,888,1,0,0.2375,0.058556,1,0,0,0.0
97,888,889,0,0,0.3500,0.045771,0,0,1,0.3
98,889,890,1,1,0.3250,0.058556,1,0,0,0.0
99,890,891,0,1,0.4000,0.015127,0,0,1,0.0

In [25]:
print(csv_df.size)

1000

In [26]:
print(excel_df.size)

214074

In [27]:
print(csv_df.shape)

(100, 10)

In [28]:
print(excel_df.shape)

(10194, 21)

In [30]:
print(csv_df.columns)

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Sex', 'Age', 'Fare',
       'Pclass_1', 'Pclass_2', 'Pclass_3', 'Family_size'],
      dtype='str')

In [32]:
print(excel_df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='str')

In [33]:
print(excel_df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='str')

In [34]:
print(csv_df.columns)

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Sex', 'Age', 'Fare',
       'Pclass_1', 'Pclass_2', 'Pclass_3', 'Family_size'],
      dtype='str')